---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: efs-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Don't matter it's elastic as k8s requires us to put something under storage
